# Advanced Programme in Deep Learning (Foundations and Applications)
## A Program by IISc and TalentSprint
### Assignment 3: Linear Algebra

## Learning Objectives

At the end of the assignment, you will be able to
* understand matrix, types of matrix, vectors and its related operations
* solve the system of linear equation using matrix solution
* implement concepts related to eigen vectors and values



### Setup Steps:

In [ ]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2237180" #@param {type:"string"}

In [ ]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "6366871391" #@param {type:"string"}

In [ ]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython
import warnings
warnings.filterwarnings("ignore")

ipython = get_ipython()
  
notebook= "M1_AST_03_Linear_Algebra_C" #name of the notebook

def setup():
    from IPython.display import HTML, display
    display(HTML('<script src="https://dashboard.talentsprint.com/aiml/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():
    ipython.magic("notebook -e "+ notebook + ".ipynb")
    
    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword()}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:        
        print(r["err"])
        return None        
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None
    
    elif getAnswer1() and getAnswer2() and getComplexity() and getAdditional() and getConcepts() and getComments() and getMentorSupport():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional, 
              "concepts" : Concepts, "record_id" : submission_id, 
              "answer1" : Answer1, "answer2" : Answer2, "id" : Id, "file_hash" : file_hash,
              "notebook" : notebook,
              "feedback_experiments_input" : Comments,
              "feedback_mentor_support": Mentor_support}
      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:        
        print(r["err"])
        return None   
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://dlfa-iisc.talentsprint.com/notebook_submissions")
        #print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
        return submission_id
    else: submission_id
    

def getAdditional():
  try:
    if not Additional: 
      raise NameError
    else:
      return Additional  
  except NameError:
    print ("Please answer Additional Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None
  
def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None
  
  
# def getWalkthrough():
#   try:
#     if not Walkthrough:
#       raise NameError
#     else:
#       return Walkthrough
#   except NameError:
#     print ("Please answer Walkthrough Question")
#     return None
  
def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None
  

def getMentorSupport():
  try:
    if not Mentor_support:
      raise NameError
    else:
      return Mentor_support
  except NameError:
    print ("Please answer Mentor support Question")
    return None

def getAnswer1():
  try:
    if not Answer1:
      raise NameError 
    else: 
      return Answer1
  except NameError:
    print ("Please answer Question 1")
    return None

def getAnswer2():
  try:
    if not Answer2:
      raise NameError 
    else: 
      return Answer2
  except NameError:
    print ("Please answer Question 2")
    return None
  

def getId():
  try: 
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup 
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup() 
else:
  print ("Please complete Id and Password cells before running setup")



Setup completed successfully


### Importing required packages

In [ ]:
import numpy as np
from math import *
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from numpy import linalg as la
from numpy.linalg import eig

### Types of Matrix

**Square Matrix**: In square matrix, the number of rows are equal to the number of columns.

1. Create a square matrix with elements 61 to 69. 

In [ ]:
square_matrix = np.array([np.arange(61,64),np.arange(64,67), np.arange(67,70)])
print("Square Matrix:\n",square_matrix)

Square Matrix:
 [[61 62 63]
 [64 65 66]
 [67 68 69]]



**Upper Triangular Matrix**: It is a type of square matrix, where all the values below the main diagonal are 0.

**Lower Triangular Matrix**: It is a type of square matrix, where all the values above the main diagonal are 0.


2. Create an upper and lower triangular matrix of size 6x6 with random values.

In [ ]:
matrix = np.random.rand(6,6)
print("Original Matrix:\n",matrix)

# Upper triangular matrix
upper_triangular = np.triu(matrix)
print("Upper Triangular Matrix:\n",upper_triangular)

# Lower triangular matrix
lower_triangular = np.tril(matrix)
print("Lower Triangular Matrix:\n", lower_triangular)

Original Matrix:
 [[0.5638518  0.73909527 0.36179455 0.34236556 0.69153017 0.45520302]
 [0.40092218 0.291692   0.1639314  0.17183217 0.31949882 0.63890714]
 [0.58836232 0.39180116 0.50958682 0.05755871 0.16045606 0.50380547]
 [0.66459481 0.83839495 0.05507834 0.08271292 0.60112941 0.54770912]
 [0.67448462 0.78961662 0.17753387 0.19661719 0.14004039 0.26967584]
 [0.01968552 0.88958861 0.80290424 0.37935841 0.13338483 0.96984886]]
Upper Triangular Matrix:
 [[0.5638518  0.73909527 0.36179455 0.34236556 0.69153017 0.45520302]
 [0.         0.291692   0.1639314  0.17183217 0.31949882 0.63890714]
 [0.         0.         0.50958682 0.05755871 0.16045606 0.50380547]
 [0.         0.         0.         0.08271292 0.60112941 0.54770912]
 [0.         0.         0.         0.         0.14004039 0.26967584]
 [0.         0.         0.         0.         0.         0.96984886]]
Lower Triangular Matrix:
 [[0.5638518  0.         0.         0.         0.         0.        ]
 [0.40092218 0.291692   0.     

**Diagonal Matrix**: In a diagonal matrix, all the values are zero except the diagonal values

3. Create a diagonal matrix of size 3x3 with integer valules and do the following:

  i). Create a diagonal matrix with the values above the diagonal elements.
  
  ii). Create a diagonal matrix with the values below the diagonal elements.





In [ ]:
M = np.array([np.arange(73,76),np.arange(32,35), np.arange(57,60)])
print("Matrix:\n",M)
 
# Diagonal Matrix
diagonal_matrix = np.diag(np.diag(M))

# Using k=1 for getting the diagonal matrix with the values above the diagonal elements
above_matrix = np.diag(np.diag(M,k=1))

# Using k=-1 for getting the diagonal matrix with the values below the diagonal elements
below_matrix = np.diag(np.diag(M,k=-1))

print("Diagonal Matrix:\n",diagonal_matrix)
print("Matrix Above Diagonal:\n",above_matrix)
print("Matrix Below Diagonal:\n",below_matrix)

Matrix:
 [[73 74 75]
 [32 33 34]
 [57 58 59]]
Diagonal Matrix:
 [[73  0  0]
 [ 0 33  0]
 [ 0  0 59]]
Matrix Above Diagonal:
 [[74  0]
 [ 0 34]]
Matrix Below Diagonal:
 [[32  0]
 [ 0 58]]


Here all the non-diagonal elements are zero.

**Identity Matrix**: A matrix of size nxn where all diagonal values are 1 and other values are 0 is an identity matrix.

4. Create a 4x4 identity matrix with integer numbers.

In [ ]:
x = np.identity(4)
print("4x4 Identity Matrix:\n", x)

y = np.identity(4,dtype=int)
print("4x4 Identity Matrix:\n", y)

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4x4 Identity Matrix:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


**Null Matrix**: A null matrix has all the values as zero.

5. Create a null matrix of integers with shape 6x6.

In [ ]:
null_matrix = np.zeros(shape=(6,6))
print("Null Matrix:\n", null_matrix)

Null Matrix:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### Matrix Transpose, Inverse, and Determinant

**Transpose**: Transpose operation flips the matrix over its diagonal i.e. replacing rows with coloums and vice-versa.

1. Create a matrix and find its transpose.

In [ ]:
# Creating a matrix
matrix1 = np.array([np.arange(0,3),np.arange(3,6)])
print("Matrix 1:\n", matrix1)

# Matrix transpose
print("Transpose of a Matrix: \n", matrix1.T)

Matrix 1:
 [[0 1 2]
 [3 4 5]]
Transpose of a Matrix: 
 [[0 3]
 [1 4]
 [2 5]]


**Inverse**: This operation helps to create a matrix such that when it is multiplied by the original matrix, the result is an identity matrix.

2. Find the inverse of a matrix.

In [ ]:
# Create a matrix
A = np.array([[5,6],[7,8]])

# Finding the inverse
inverse = np.linalg.inv(A)
print("Inverse of matrix:\n",inverse)

Inverse of matrix:
 [[-4.   3. ]
 [ 3.5 -2.5]]


3. Create 3x3 matrix and find the inverse of it.

In [ ]:
B = np.array([[1,9,3],[4,5,6],[7,8,9]])
print("Matrix B:\n", B)

# Finding Inverse 
inverse = np.linalg.inv(B)
print("Inverse of matrix:\n",inverse)

Matrix B:
 [[1 9 3]
 [4 5 6]
 [7 8 9]]
Inverse of matrix:
 [[-0.07142857 -1.35714286  0.92857143]
 [ 0.14285714 -0.28571429  0.14285714]
 [-0.07142857  1.30952381 -0.73809524]]


**Determinant**: Determinant of a matrix is a scalar value that helps to characterize the properties of a matrix.

4. Create a matrix of size 3x3 and find the determinant of it.

  To know more about Python libraries, click [here](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html)




In [ ]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = la.det(B)
print(D)

0.0


5. Create a 4x4 matrix and slice the rows and columns to get the middle sub-matrix and find its determinant.

In [ ]:
# Create 4x4 matrix
matrix_new = np.array([np.arange(0,4),np.arange(4,8),np.arange(8,12),np.arange(12,16)])
print("Matrix:\n", matrix_new)

# Slicing of rows and columns
sliced_matrix = matrix_new[1:3,1:3]
print("Sliced Matrix:\n",sliced_matrix)

# Finding the determinant
determinant = np.linalg.det(sliced_matrix)
print("Determinant Value:\n", determinant)

Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sliced Matrix:
 [[ 5  6]
 [ 9 10]]
Determinant Value:
 -4.000000000000003



### Matrix Operations and Functions


### Addition 

1. Create matrix and add a scalar to it.





In [ ]:
matrix1 = np.array([np.arange(27,32),np.arange(53,58),np.arange(33,38),np.arange(91,96)])
print("Original Matrix:\n",matrix1)

# Scalar Addition
Scalar_add = matrix1 + 1
print("Resulting Matrix:\n",Scalar_add)

Original Matrix:
 [[27 28 29 30 31]
 [53 54 55 56 57]
 [33 34 35 36 37]
 [91 92 93 94 95]]
Resulting Matrix:
 [[28 29 30 31 32]
 [54 55 56 57 58]
 [34 35 36 37 38]
 [92 93 94 95 96]]


2. Create two matrices as matrix1 & matrix2. Then, perform addition operation on them.










In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(7,10),np.arange(24,27)])
matrix2 = np.array([np.arange(16,19),np.arange(33,36)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Addition
Matrix_addition = matrix1 + matrix2
print("Matrix Addition: \n",Matrix_addition)

Matrix 1:
 [[ 7  8  9]
 [24 25 26]]
Matrix 2:
 [[16 17 18]
 [33 34 35]]
Matrix Addition: 
 [[23 25 27]
 [57 59 61]]


### Subtraction

3. Create a matrix of size 3x6 and subtract a scalar from it.



In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(5,11), np.arange(47,53), np.arange(9,15)])
print("Matrix 1:\n", matrix1)

# Scalar Substraction
Scalar_sub = matrix1 - np.sin(np.pi/4)
print("Scalar Subtraction :\n",Scalar_sub)

Matrix 1:
 [[ 5  6  7  8  9 10]
 [47 48 49 50 51 52]
 [ 9 10 11 12 13 14]]
Scalar Subtraction :
 [[ 4.29289322  5.29289322  6.29289322  7.29289322  8.29289322  9.29289322]
 [46.29289322 47.29289322 48.29289322 49.29289322 50.29289322 51.29289322]
 [ 8.29289322  9.29289322 10.29289322 11.29289322 12.29289322 13.29289322]]


4. Create two matrices of size 2x3 and subtract second matrix from the first one.

In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(0,3),np.arange(3,6)])
matrix2 = np.array([np.arange(6,9),np.arange(9,12)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Subtraction
Matrix_subtraction = matrix1 - matrix2
print(Matrix_subtraction)

Matrix 1:
 [[0 1 2]
 [3 4 5]]
Matrix 2:
 [[ 6  7  8]
 [ 9 10 11]]
[[-6 -6 -6]
 [-6 -6 -6]]


### Division

5. Create a 4x3 matrix and divide it by a scalar.






In [ ]:
matrix1 = np.array([np.arange(6,9),np.arange(14,17),np.arange(97,100),np.arange(54,57)])
print("Matrix 1:\n", matrix1)

# Scalar Division
Scalar_div = matrix1/np.cos(np.pi/2)
print("Scalar Division: \n",Scalar_div)

Matrix 1:
 [[ 6  7  8]
 [14 15 16]
 [97 98 99]
 [54 55 56]]
Scalar Division: 
 [[9.79874361e+16 1.14318675e+17 1.30649915e+17]
 [2.28637351e+17 2.44968590e+17 2.61299830e+17]
 [1.58413022e+18 1.60046146e+18 1.61679270e+18]
 [8.81886925e+17 8.98218164e+17 9.14549404e+17]]


6. Create two matrices and divide the first matrix by the second one.

In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(18,21),np.arange(32,35)])
matrix2 = np.array([np.arange(6,9),np.arange(9,12)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Division
Matrix_div = matrix1/matrix2
print(Matrix_div)

Matrix 1:
 [[18 19 20]
 [32 33 34]]
Matrix 2:
 [[ 6  7  8]
 [ 9 10 11]]
[[3.         2.71428571 2.5       ]
 [3.55555556 3.3        3.09090909]]


### Multiplication

7. Create a matrix and mulitply it by a Scalar.




In [ ]:
matrix1 = np.array([np.arange(121,126),np.arange(75,80)])
print("Matrix 1:\n", matrix1)

# Scalar Product
Scalar_product = matrix1*np.sin(3*np.pi/4)
print("Scalar Product:\n", Scalar_product)

Matrix 1:
 [[121 122 123 124 125]
 [ 75  76  77  78  79]]
Scalar Product:
 [[85.55992052 86.2670273  86.97413409 87.68124087 88.38834765]
 [53.03300859 53.74011537 54.44722215 55.15432893 55.86143571]]


Multiplication of two matrices is shown in the below diagram:



$A.B = \begin{bmatrix}
a & b\\
c & d\\
\end{bmatrix} \begin{bmatrix}
e & f\\
g & h\\
\end{bmatrix} = \begin{bmatrix}
ae+ bg & af+bh\\
ce+dg & cf+dh\\
\end{bmatrix}$

8. Create two matrices and multiply them.

  Note: Here, the corresponding elements are not multiplied. The multiplication rules are different from addition, subtraction, and division. 

In [ ]:
# Creating matrices
matrix1 = np.array([np.arange(5,9),np.arange(2,6)])
matrix2 = np.array([np.arange(6,8),np.arange(12,14),np.arange(4,6),np.arange(1,3)])
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Dot Product
Dot_product = np.dot(matrix1, matrix2)
print("Dot Product: \n",Dot_product)

Matrix 1:
 [[5 6 7 8]
 [2 3 4 5]]
Matrix 2:
 [[ 6  7]
 [12 13]
 [ 4  5]
 [ 1  2]]
Dot Product: 
 [[138 164]
 [ 69  83]]



### Cross Product & Dot Product of Vector and Matrices


*   **Cross Product** : In three-dimensional space, the cross product is a binary operation between two vectors. It produces a perpendicular vector to both vectors.

<center><img src="https://cdn.iisc.talentsprint.com/DLFA/Experiment_related_data/cross_product.png" alt="Drawing" height="300" width="280"/></center>

*   **Dot Product** : The dot product is defined algebraically as the sum of the products of the corresponding entries of the two number sequences. Moreover, it is the product of the Euclidean magnitudes and the cosine of the angle between them.

<br>
<center>
<img src="https://cdn.iisc.talentsprint.com/DLFA/Experiment_related_data/dot_product-01.png" alt="Drawing" height="300" width="300"/></center>


1. Create two matrices and perform cross product on them.

In [ ]:
a = np.array([[4,8,9],[6,5,2]])
b = np.array([[1,4,8],[3,7,5]])
print("Matrix a\n",a)
print("Matrix b\n",b)

# Cross Product
cproduct = np.cross(a,b)
print("Cross Product of Matrices:\n",cproduct)

Matrix a
 [[4 8 9]
 [6 5 2]]
Matrix b
 [[1 4 8]
 [3 7 5]]
Cross Product of Matrices:
 [[ 28 -23   8]
 [ 11 -24  27]]


2. Apply dot product on the below given vectors:

    i). x = sin 45 + 6i
    
    ii).   y = 42 + 7i



In [ ]:
# Taking two 1D arrays
y = [42,7]
x = [sin(np.pi/4),6]

# Calculating dot product using dot() method
print(np.dot(x, y))

3. Create two vectors and perform cross product operation on them.


In [ ]:
a = [5,6,1]
b = [2,5,9]

# Cross Product
cross_product = np.cross(a,b)
print("Cross Product of Vectors:\n",cross_product)

Cross Product of Vectors:
 [ 49 -43  13]


### System of Linear Equations

1. Solve the following linear equation for x and y using matrix solution.

  i). 7x + 3y = 34

  ii). 8x + 9y = 50

    Hint: Use the equation for AX = B to solve the equation where A & B are the matrices for values of LHS and RHS of the equation and X consist of x & y variables.
    
    To know more about Python libraries, [here ](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)
 







Steps to solve:

1. Write the equation in the form of $AX = B$
2. Then, you can write it as -> $X = A^{-1}.B$ 

In [ ]:
A = np.array([[7,3],[8,9]])
X = np.array([[x],[y]])
B = np.array([[34],[50]])

# Inverse of matrix A
A1= np.linalg.inv(A)

# Dot product of matrix A1 and B
X = np.dot(A1,B)
print("Dot product of matrix A1 and B:\n",X)

Dot product of matrix A1 and B:
 [[4.]
 [2.]]


2. Find the values of x and y from the system of linear equations given below and verify the solution:

  i). 6x + 5y = 19

  ii). 7x + 9y = 32







Steps to solve:

1. Create two arrays. 

2. Solve for x and y.

3. Compute the dot product of the matrix equation(array) and the solution

4. Use allclose() method to check whether the matrices are element-wise equal or not.

In [ ]:
# Creating arrays
m = np.array([[6,5],[7,9]])
n = np.array([19,32])

# Solve a linear matrix equation
values = np.linalg.solve(m,n)
print("Values:\n",values) 

# Verify the solution
p = np.dot(m,values)
result = np.allclose(p,n)

print("Result:\n",result)

Values:
 [0.57894737 3.10526316]
Result:
 True


3. Below are pair of three linear equations. Find the values of x, y, & z.

  i). 8x + 3y + 5z = 29

  ii). 4x + 7y + 12z = 54

  iii). 9x + 5y + 11z = 52







In [ ]:
A = np.array([[8,3,5],[4,7,12],[9,5,11]])
B = np.array([29,54,52])

# Inverse of matrix A
A1 = np.linalg.inv(A)

# Dot product of A1 and B
X = np.dot(A1,B)
print("Dot product of A1 and B\n",X)

Dot product of A1 and B
 [1. 2. 3.]


4. Suppose an automobile company sells 25 bikes and 32 scooties in January. In the next month the sale goes up to 30 bikes and 41 scooties. The total revenue generated is Rs. 506,000 and Rs.620,000 for the respective months. 
Find the cost of bike and scooty using matrix solution.

  Hint: Form the pair of linear equations using the below problem statement and solve the equations to get the answer.

    Assume the cost of bike and scooty as x and y. Moreover, we can create the equation:

       i)   25x + 32y = 506000

       ii)  30x + 41y = 628000



In [ ]:
# Create matrices using the values from the equation
A = np.array([[25,32],[30,41]]) 
B = np.array([506000,628000]) 

# Inverse of matrix A 
A1 = np.linalg.inv(A) 

# Dot product of A1 and B
X = np.dot(A1,B) 
print("Dot product of A1 and B\n",X)   

Dot product of A1 and B
 [10000.  8000.]


### Checking the Linear Dependence and Independence 

We use linear dependence and independence to check the relation of the variables in the real-world dataset.

1. Check linear dependence for the following equations.

  i). 6x + 3y + 5z = 19 

  ii). 2x + y + 7z = 17  

  iii). 16x + 8y + 40z = 104  

  Hint : If the determinant is 0 then it is linearly dependent.





In [ ]:
# Creating arrays
A = np.array([[6,3,5],[2,1,7],[16,8,40]])
print("A:\n",A)

# Finding determinant
d = np.linalg.det(A)
print("Determinant =",d)

if(d==0):
  print(" Ther are linearly dependent as determinant is 0")

A:
 [[ 6  3  5]
 [ 2  1  7]
 [16  8 40]]
Determinant = 0.0
 Ther are linearly dependent as determinant is 0


2. Find whether the below linear equations are linearly dependent or independent.

  i). 4x + 2y = 6

  ii). y = -x-2


In [ ]:
a = np.array([[4,2],[1,1]])
print(a)

# Finding determinant
determinant = np.linalg.det(a)
print("Determinant:\n",determinant)

if(determinant!=0):
  print("The equations are linearly independent")

[[4 2]
 [1 1]]
Determinant:
 2.0
The equations are linearly independent


### Eigen Vectors and Values

Eigen values and vectors are specifically used to define the characterstics of a matrix which is a form of representing data. So, when we train a Machine Learning or Deep Learning model there are chances where unncessary data is punched for training. Thus, using eigen vectors and values we can reduce the training data by knowing its characterstics.


**Eigen Vector**: A non-zero vector that changes by a scalar factor when a linear transformation is applied is known as an eigenvector. 

**Eigen Values**: When a linear transformation is applied to an eigenvector, the eigenvector is scaled by a particular value which is called eigenvalue.

1. Create a matrix and find the eigen vectors and eigen values for it.

In [ ]:
# Create a matrix
A = np.array([[2,6],[3,5]])
print("Array:\n",A)

# Calculating eigen vectors and eigen values
val,vec = np.linalg.eig(A)

print("Eigen Value:\n",val)
print("Eigen Vector:\n",vec)

Array:
 [[2 6]
 [3 5]]
Eigen Value:
 [-1.  8.]
Eigen Vector:
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


2. Confirm that the vector for the below matrix is an eigen vector of the matrix.

  Hint: Equate the multiplication of first eigen 
vector with multiplication of first eigen vector and first eigen value.






In [ ]:
# Defining a matrix
M = np.array([[3,2,7],[5,8,9],[9,3,7]])

# Finding eigen vectors and values
val,vec = eig(M)

# Finding first vector
N = np.dot(M,vec[:,0])
print("First Vector:\n", N)

# Finding second vector
P = vec[:,0]*val[0]
print("Second Vector:\n",P)

First Vector:
 [ -6.47873562 -12.80096521  -9.48334439]
Second Vector:
 [ -6.47873562 -12.80096521  -9.48334439]


### Please answer the questions below to complete the experiment:




Consider the statements given below and answer Q1.


A. Every skew-symmetric matrix of odd order is non-singular

B. If determinant of a square matrix is non-zero, then it is non singular

C. Adjoint of symmetric matrix is symmetric

D. Adjoint of a diagonal matrix is diagonal

In [ ]:
#@title Q.1. Which of the above statements is/are False?
Answer1 = "Only A" #@param ["","Only A","Both A & B","Only B", "Only C", "Both B & C"]


Consider the matrix A and the values of a, b, and c given below for answering Q.2.

$A = \begin{bmatrix}
0 & 2b & c   \\
a & b & -c   \\
a & -b & c   \\
\end{bmatrix}$

<br>

A). a = $\pm \frac{1}{\sqrt{6}} $, b = $\pm \frac{1}{\sqrt{2}}$ , c = $\pm \frac{1}{\sqrt{2}} $


<br>

B). a = $\pm \frac{1}{\sqrt{6}} $, b = $\pm \frac{1}{\sqrt{3}}$ , c = $\pm \frac{1}{\sqrt{2}} $


<br>

C). a = $\pm \frac{1}{\sqrt{2}} $, b = $\pm \frac{1}{\sqrt{6}}$ , c = $\pm \frac{1}{\sqrt{3}} $

<br>

D). a = $\pm \frac{1}{\sqrt{2}} $, b = $\pm \frac{1}{\sqrt{2}}$ , c = $\pm \frac{1}{\sqrt{2}} $

In [ ]:
#@title Q.2. If 'A' is an orthogonal matrix, then, what will be the values of a, b, and c. 
Answer2 = "Only C" #@param ["","Only A","Only B","Only C","Only D", "None of the above"]


In [ ]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "Good, But Not Challenging for me" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [ ]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "None" #@param {type:"string"}


In [ ]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "Yes" #@param ["","Yes", "No"]


In [ ]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "Somewhat Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "Somewhat Useful" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Run this cell to submit your notebook for grading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")

Your submission is successful.
Ref Id: 332
Date of submission:  21 Jan 2023
Time of submission:  20:13:24
View your submissions: https://dlfa-iisc.talentsprint.com/notebook_submissions
